Reverted API version because of: "java.lang.NoClassDefFoundError: org/netbeans/modules/csl/spi/DefaultLanguageConfig while loading com.welovecoding.netbeans.plugin.editorconfig.editor.csl.EditorConfigLanguage"